# Generated by Django 2.1.1 on 2018-10-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walk',
            name='district',
        ),
        migrations.AddField(
            model_name='walk',
            name='district',
            field=models.ManyToManyField(help_text='Select a District(s)', to='paths.District'),
        ),
        migrations.RemoveField(
            model_name='walk',
            name='subdistrict',
        ),
        migrations.AddField(
            model_name='walk',
            name='subdistrict',
            field=models.ManyToManyField(help_text='Select a Subdistrict(s)', to='paths.Subdistrict'),
        ),
    ]
