# Generated by Django 2.1 on 2018-10-07 00:02

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_auto_20181005_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geowalk',
            name='geom',
            field=djgeojson.fields.LineStringField(),
        ),
    ]
