# Generated by Django 2.1.1 on 2018-10-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_auto_20181001_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdistrict',
            name='district',
        ),
        migrations.AddField(
            model_name='subdistrict',
            name='district',
            field=models.ManyToManyField(to='paths.District'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='duration',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='walk',
            name='length',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
