# Generated by Django 2.1.1 on 2018-10-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0003_auto_20181001_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='slug',
            field=models.SlugField(default='none', unique=True),
        ),
    ]
