# Generated by Django 2.1 on 2018-10-21 22:54

from django.db import migrations, models
from promenade.utils import unique_slug_generator

def update_slug(apps, schema_editor):
    GeoWalk = apps.get_model('paths', 'GeoWalk')

    for walk in GeoWalk.objects.all():
        if not walk.slug:
            walk.slug = unique_slug_generator(walk, walk.name, walk.slug)
            walk.save()

class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0004_geowalk_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geowalk',
            name='slug',
            field=models.SlugField(max_length=70, unique=True),
        ),
    ]
