# Generated by Django 2.1.1 on 2018-10-02 19:55

from django.db import migrations, models
from promenade.utils import unique_slug_generator

def update_slug(apps, schema_editor):
    Walk = apps.get_model('paths', 'Walk')

    for instance in Walk.objects.all():
        if not instance.slug:
            instance.slug = unique_slug_generator(instance, instance.name, instance.slug)
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0005_auto_20181001_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='description',
            field=models.TextField(help_text='Describe the Walk', max_length=150),
        ),
        migrations.AlterField(
            model_name='walk',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.RunPython(update_slug, reverse_code=migrations.RunPython.noop)
        
    ]
