# Generated by Django 2.1.1 on 2018-10-03 00:52

from django.db import migrations, models
from promenade.utils import unique_slug_generator

def update_slug(apps, schema_editor):
    Walk = apps.get_model('paths', 'Walk')
    District = apps.get_model('paths', 'District')
    Sub = apps.get_model('paths', 'Subdistrict')

    for instance in Walk.objects.all():
        if not instance.slug:
            instance.slug = unique_slug_generator(instance, instance.name, instance.slug)
            instance.save()

    for instance in District.objects.all():
        if not instance.slug:
            instance.slug = unique_slug_generator(instance, instance.name, instance.slug)
            instance.save()

    for instance in Sub.objects.all():
        if not instance.slug:
            instance.slug = unique_slug_generator(instance, instance.name, instance.slug)
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0007_auto_20181002_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='subdistrict',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.RunPython(update_slug, reverse_code=migrations.RunPython.noop)
    ]
