# Generated by Django 2.1 on 2018-10-26 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0009_walkcomment_walk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkcomment',
            name='walk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walks', to='paths.GeoWalk'),
        ),
    ]
