# Generated by Django 2.1 on 2018-10-26 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0010_auto_20181025_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkcomment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walks', to=settings.AUTH_USER_MODEL),
        ),
    ]
